#!/usr/bin/env bash
# =============================================================================
# setup.sh — Configure the agent harness for your project.
#
# Run this once after copying .claude/ into your project:
#   chmod +x setup.sh && ./setup.sh
#
# What it does:
#   1. Asks configuration questions
#   2. Writes values to .claude/hooks/harness.config.sh
#   3. Makes all hook scripts executable
#   4. Adds .claude/logs/, .claude/handoff/, .claude/transcripts/, .claude/worktrees/
#      to .gitignore (if not already there)
#   5. Prints a summary and next steps
# =============================================================================

set -euo pipefail

REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
CONFIG="$REPO_ROOT/.claude/hooks/harness.config.sh"

echo ""
echo "========================================"
echo "  Agent Harness Setup"
echo "========================================"
echo ""
echo "This will configure the harness for your project."
echo "Press Enter to accept defaults (shown in brackets)."
echo ""

# ──────────────────────────────────────────────────────────────────────────────
# Gather inputs
# ──────────────────────────────────────────────────────────────────────────────

read -p "App / project name [My Project]: " APP_NAME
APP_NAME="${APP_NAME:-My Project}"

read -p "Package manager (pnpm/npm/yarn/bun) [pnpm]: " PKG_MGR
PKG_MGR="${PKG_MGR:-pnpm}"

read -p "Source directory pattern (pipe-separated, e.g. src|lib|apps) [src]: " SRC_DIRS
SRC_DIRS="${SRC_DIRS:-src}"

read -p "Test command [${PKG_MGR} test]: " TEST_CMD
TEST_CMD="${TEST_CMD:-${PKG_MGR} test}"

read -p "Typecheck command (blank to skip) [${PKG_MGR} run typecheck]: " TYPECHECK_CMD
TYPECHECK_CMD="${TYPECHECK_CMD:-${PKG_MGR} run typecheck}"

read -p "Lint command [${PKG_MGR} run lint]: " LINT_CMD
LINT_CMD="${LINT_CMD:-${PKG_MGR} run lint}"

read -p "Format command [${PKG_MGR} run format]: " FORMAT_CMD
FORMAT_CMD="${FORMAT_CMD:-${PKG_MGR} run format}"

read -p "Build command [${PKG_MGR} run build]: " BUILD_CMD
BUILD_CMD="${BUILD_CMD:-${PKG_MGR} run build}"

read -p "Dev server command [${PKG_MGR} run dev]: " DEV_CMD
DEV_CMD="${DEV_CMD:-${PKG_MGR} run dev}"

read -p "Dev server port [3000]: " DEV_PORT
DEV_PORT="${DEV_PORT:-3000}"

read -p "Lockfile name [${PKG_MGR}-lock.yaml]: " LOCK_FILE
LOCK_FILE="${LOCK_FILE:-${PKG_MGR}-lock.yaml}"
# Normalize common lock file names
case "$PKG_MGR" in
  npm)  LOCK_FILE="${LOCK_FILE:-package-lock.json}" ;;
  yarn) LOCK_FILE="${LOCK_FILE:-yarn.lock}" ;;
  bun)  LOCK_FILE="${LOCK_FILE:-bun.lockb}" ;;
esac

echo ""
echo "Database setup (press Enter to skip if no DB):"
read -p "DB schema file path (relative to repo root, e.g. src/db/schema.ts) [blank]: " DB_SCHEMA
read -p "DB generate command (e.g. ${PKG_MGR} run db:generate) [blank]: " DB_GENERATE
read -p "DB push command (e.g. ${PKG_MGR} run db:push) [blank]: " DB_PUSH
read -p "DB migrations directory (e.g. prisma/migrations) [blank]: " DB_MIGRATIONS

echo ""
read -p "Required env vars for pre-deploy check (space-separated, e.g. DATABASE_URL API_KEY) [blank]: " REQUIRED_ENV

# ──────────────────────────────────────────────────────────────────────────────
# Write harness.config.sh
# ──────────────────────────────────────────────────────────────────────────────

cat > "$CONFIG" <<EOF
#!/usr/bin/env bash
# =============================================================================
# harness.config.sh — Project-specific configuration for the agent harness.
# Generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Edit directly to update values.
# =============================================================================

HARNESS_PKG_MGR="${PKG_MGR}"
HARNESS_SRC_DIRS="${SRC_DIRS}"
HARNESS_TEST_CMD="${TEST_CMD}"
HARNESS_TYPECHECK_CMD="${TYPECHECK_CMD}"
HARNESS_LINT_CMD="${LINT_CMD}"
HARNESS_FORMAT_CMD="${FORMAT_CMD}"
HARNESS_BUILD_CMD="${BUILD_CMD}"
HARNESS_APP_NAME="${APP_NAME}"
HARNESS_DEV_PORT="${DEV_PORT}"
HARNESS_DEV_CMD="${DEV_CMD}"
HARNESS_DEV_PROCESS="node"
HARNESS_LOCK_FILE="${LOCK_FILE}"
HARNESS_DB_SCHEMA_PATH="${DB_SCHEMA:-}"
HARNESS_DB_GENERATE_CMD="${DB_GENERATE:-}"
HARNESS_DB_PUSH_CMD="${DB_PUSH:-}"
HARNESS_DB_MIGRATIONS_DIR="${DB_MIGRATIONS:-}"
HARNESS_FORMATTABLE_EXTS="ts|tsx|js|jsx|json|css"
HARNESS_REQUIRED_ENV_VARS="${REQUIRED_ENV:-}"
EOF

echo "Wrote $CONFIG"

# ──────────────────────────────────────────────────────────────────────────────
# Generate conductor.json
# ──────────────────────────────────────────────────────────────────────────────

echo ""
read -p "Generate conductor.json for Conductor workspace scripts? [Y/n]: " GEN_CONDUCTOR
GEN_CONDUCTOR="${GEN_CONDUCTOR:-Y}"

if [[ "$GEN_CONDUCTOR" =~ ^[Yy]$ ]]; then
  CONDUCTOR_JSON="$REPO_ROOT/conductor.json"

  # Compose setup script: install deps, then copy .env.example if present,
  # then run DB generate + push if configured.
  SETUP_LINES=("${PKG_MGR} install")
  if [ -f "$REPO_ROOT/.env.example" ]; then
    SETUP_LINES+=("if [ ! -f .env ]; then cp .env.example .env; fi")
  fi
  if [ -n "${DB_GENERATE:-}" ]; then
    SETUP_LINES+=("${DB_GENERATE}")
  fi
  if [ -n "${DB_PUSH:-}" ]; then
    SETUP_LINES+=("${DB_PUSH}")
  fi
  # Join with &&
  SETUP_SCRIPT=$(printf "%s && " "${SETUP_LINES[@]}")
  SETUP_SCRIPT="${SETUP_SCRIPT% && }"

  # Archive script: stop dev server on the workspace's assigned port + clean
  # build artifacts. CONDUCTOR_PORT is expanded at archive time so each
  # workspace kills its own dev server; falls back to the configured default
  # when running outside a Conductor workspace.
  ARCHIVE_SCRIPT="PIDS=\$(lsof -ti:\${CONDUCTOR_PORT:-${DEV_PORT}} 2>/dev/null || true); [ -n \"\$PIDS\" ] && kill -TERM \$PIDS 2>/dev/null || true; rm -rf node_modules .next .turbo dist build .cache"

  # Write conductor.json via jq for safe quoting.
  jq -n \
    --arg setup "$SETUP_SCRIPT" \
    --arg run "$DEV_CMD" \
    --arg archive "$ARCHIVE_SCRIPT" \
    '{scripts: {setup: $setup, run: $run, archive: $archive}}' > "$CONDUCTOR_JSON"

  echo "Wrote $CONDUCTOR_JSON"
  echo ""
  echo "  setup:   $SETUP_SCRIPT"
  echo "  run:     $DEV_CMD"
  echo "  archive: $ARCHIVE_SCRIPT"
  echo ""
  echo "Review and edit conductor.json before committing — the archive script"
  echo "removes build artifacts aggressively. Adjust for your stack."
fi

# ──────────────────────────────────────────────────────────────────────────────
# Make hooks executable
# ──────────────────────────────────────────────────────────────────────────────

chmod +x "$REPO_ROOT/.claude/hooks/"*.sh
echo "Made hooks executable"

# ──────────────────────────────────────────────────────────────────────────────
# Update .gitignore
# ──────────────────────────────────────────────────────────────────────────────

GITIGNORE="$REPO_ROOT/.gitignore"
touch "$GITIGNORE"

add_gitignore() {
  local pattern="$1"
  if ! grep -qF "$pattern" "$GITIGNORE"; then
    echo "$pattern" >> "$GITIGNORE"
    echo "Added $pattern to .gitignore"
  fi
}

echo "" >> "$GITIGNORE"
echo "# Agent harness — ephemeral files" >> "$GITIGNORE"
add_gitignore ".claude/logs/"
add_gitignore ".claude/handoff/"
add_gitignore ".claude/transcripts/"
add_gitignore ".claude/worktrees/"

# ──────────────────────────────────────────────────────────────────────────────
# Verify settings.json exists
# ──────────────────────────────────────────────────────────────────────────────

if [ ! -f "$REPO_ROOT/.claude/settings.json" ]; then
  echo "WARNING: .claude/settings.json not found. Copy it from the agent-harness repo."
fi

# ──────────────────────────────────────────────────────────────────────────────
# Summary
# ──────────────────────────────────────────────────────────────────────────────

echo ""
echo "========================================"
echo "  Setup complete!"
echo "========================================"
echo ""
echo "Configuration written to: .claude/hooks/harness.config.sh"
echo ""
echo "Next steps:"
echo "  1. Review .claude/hooks/harness.config.sh and adjust if needed"
echo "  2. Add .claude/settings.json to your project if not already there"
echo "  3. Add a CLAUDE.md to your project documenting conventions"
echo "  4. Run: claude /harness-health"
echo "     to verify everything is wired up correctly"
echo ""
echo "Workflow:"
echo "  /weekly-goals  → /demo-script → /plan-sprint → /build → /sync"
echo ""
