#!/usr/bin/env bash
# PreToolUse hook for Edit|Write|MultiEdit — blocks edits to protected files
set -euo pipefail

REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
# shellcheck source=config.sh
source "$REPO_ROOT/.claude/hooks/config.sh" 2>/dev/null || true

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

# Normalize to basename and relative path
BASENAME=$(basename "$FILE_PATH")
REL_PATH="$FILE_PATH"
if [ -n "$REPO_ROOT" ]; then
  REL_PATH="${FILE_PATH#$REPO_ROOT/}"
fi

block() {
  echo '{"decision": "block", "reason": "'"$1"'"}' >&2
  exit 2
}

# Block .env files
if [[ "$BASENAME" == ".env" || "$BASENAME" == .env.* ]]; then
  block "Editing $BASENAME is not allowed — environment files must be managed manually"
fi

# Block hook scripts (guard the guards) — cover both the symlinked .claude/hooks/
# surface and the canonical hooks/shell/, hooks/config.sh, hooks/pi/ paths.
if [[ "$REL_PATH" == .claude/hooks/* \
   || "$REL_PATH" == hooks/shell/* \
   || "$REL_PATH" == hooks/config.sh \
   || "$REL_PATH" == hooks/pi/* ]]; then
  block "Editing hook scripts is not allowed — they enforce quality gates"
fi

# Block settings.json (hook config)
if [[ "$REL_PATH" == ".claude/settings.json" ]]; then
  block "Editing .claude/settings.json is not allowed — it contains hook configuration"
fi

# Block lockfile (auto-generated)
if [[ "$BASENAME" == "$HARNESS_LOCK_FILE" ]]; then
  block "Editing $HARNESS_LOCK_FILE is not allowed — it is auto-generated by the package manager"
fi

exit 0
