import { basename } from "node:path";

export interface ProtectedFilesConfig {
  HARNESS_LOCK_FILE?: string;
}

export type ProtectedResult = { block: true; reason: string } | undefined;

/**
 * Pure check function — returns { block, reason } if a path should be
 * blocked from edit/write/multi_edit. Otherwise undefined.
 *
 * Mirrors the rules from hooks/shell/protected-files.sh, plus host-neutral
 * additions: also blocks the canonical hooks/ tree (shell + pi extensions)
 * and the Pi settings.json.
 */
export function checkProtectedFile(
  path: string,
  cfg: ProtectedFilesConfig,
): ProtectedResult {
  const base = basename(path);

  // Rule 1: .env files (basename starts with .env).
  if (base === ".env" || /^\.env\.[A-Za-z0-9_-]+$/.test(base)) {
    return {
      block: true,
      reason: `Editing ${base} is not allowed — environment files must be managed manually.`,
    };
  }

  // Rule 2: settings.json under either .claude/ or .pi/.
  if (/(?:^|\/)(?:\.claude|\.pi)\/settings\.json$/.test(path)) {
    return {
      block: true,
      reason:
        "Editing settings.json is not allowed — it contains hook configuration.",
    };
  }

  // Rule 3: hook scripts (both runtime .claude/hooks and canonical hooks/shell + hooks/pi).
  if (
    /(?:^|\/)\.claude\/hooks\//.test(path) ||
    /(?:^|\/)hooks\/(?:shell|pi)\//.test(path)
  ) {
    return {
      block: true,
      reason:
        "Editing hook scripts is not allowed — they enforce quality gates.",
    };
  }

  // Rule 4: the harness config file itself.
  if (/(?:^|\/)hooks\/config\.sh$/.test(path)) {
    return {
      block: true,
      reason:
        "Editing hooks/config.sh is not allowed — re-run setup.sh to update.",
    };
  }

  // Rule 5: lockfile (basename match against config-driven name).
  if (cfg.HARNESS_LOCK_FILE && base === cfg.HARNESS_LOCK_FILE) {
    return {
      block: true,
      reason: `Editing ${base} is not allowed — lockfile is auto-generated by the package manager.`,
    };
  }

  return undefined;
}
